db/migrate/20230805015343_add_username_to_users.rb
db/migrate/20230805015551_add_duedate_to_users.rb
db/schema.rb

added username and due_date to users

added columns to user

---

app/models/appointment.rb
app/models/attendant.rb
app/models/event.rb
app/models/hospital.rb
app/models/post.rb
app/models/reply.rb
app/models/user.rb
db/migrate/20230805033822_create_hospitals.rb
db/migrate/20230805033915_create_appointments.rb
db/migrate/20230805033939_create_posts.rb
db/migrate/20230805034007_create_replies.rb
db/migrate/20230805034021_create_events.rb
db/migrate/20230805034033_create_attendants.rb
db/migrate/20230805034054_add_username_to_users.rb
db/migrate/20230805034110_add_duedate_to_users.rb
db/schema.rb
test/models/appointment_test.rb
test/models/attendant_test.rb
test/models/event_test.rb
test/models/hospital_test.rb
test/models/post_test.rb
test/models/reply_test.rb

finished adding the models.
also added username and due-date to users table
We need to add validations and dependencies at some point.
e.g replies are deleted when posts are deleted

finished models

---

app/assets/stylesheets/components/_navbar.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_banner.html.erb
app/views/shared/_navbar.html.erb

Creating homepage

---

app/controllers/application_controller.rb
app/controllers/hospitals_controller.rb
app/controllers/posts_controller.rb
app/policies/hospital_policy.rb
app/policies/post_policy.rb
test/policies/post_policy_test.rb

edited pundit for hospitals and posts

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/application_controller.rb
app/controllers/users_controller.rb
app/policies/user_policy.rb
app/views/hospitals/index.html.erb
app/views/layouts/application.html.erb
app/views/posts/index.html.erb
app/views/posts/new.html.erb
app/views/posts/show.html.erb
app/views/shared/_banner.html.erb
app/views/shared/_navbar.html.erb
app/views/users/calendar.html.erb
app/views/users/show.html.erb
config/routes.rb
test/controllers/users_controller_test.rb
test/policies/user_policy_test.rb

I've been working on few thing since last time.
Navbar links are leading to the right page
Styled few pages so that they don't overlap with the navbar
Create a Calendar and Profile page 
I create some variable in SCSS for the color so please go check app/assets/stylesheets/config/_colors.scss 
I tried also to work on the log out button but it is NOT working YET.[](url)

Navbar link

---

app/controllers/application_controller.rb
app/javascript/application.js
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb
app/views/users/show.html.erb

add missing js tag

---

app/controllers/hospitals_controller.rb
app/controllers/reviews_controller.rb
app/models/hospital.rb
app/models/review.rb
app/policies/review_policy.rb
app/views/hospitals/index.html.erb
app/views/hospitals/show.html.erb
app/views/reviews/new.html.erb
config/routes.rb
db/migrate/20230810114258_create_reviews.rb
db/migrate/20230810121911_add_title_to_reviews.rb
db/schema.rb
test/controllers/reviews_controller_test.rb
test/models/review_test.rb

user can create a review on the hospital show page. Can improve it by sorting out the order, maybe display 1-3 and a "see more" button

finished initial review setup

---

app/assets/stylesheets/components/_navbar.scss
app/controllers/posts_controller.rb
app/controllers/replies_controller.rb
app/models/reply.rb
app/policies/reply_policy.rb
app/views/hospitals/index.html.erb
app/views/posts/index.html.erb
app/views/posts/new.html.erb
app/views/posts/show.html.erb
config/routes.rb
db/seeds.rb

Also started search function in posts!

User replies to posts

---

app/views/shared/_navbar.html.erb
db/schema.rb

fixed navbar links

---

app/views/users/calendar.html.erb

modal on the calendar now includes appoinements and events

fixed modal for events

---

app/views/events/index.html.erb
app/views/events/show.html.erb
app/views/shared/_banner.html.erb
app/views/users/calendar.html.erb

fixed events index,
events show and banner for events and calendar

fixed missing div in the events pages and update banner

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_accordian.scss
app/assets/stylesheets/components/_index.scss
app/controllers/users_controller.rb
app/javascript/controllers/index.js
app/models/article.rb
app/views/users/show.html.erb
db/migrate/20230819025719_create_articles.rb
db/schema.rb
db/seeds.rb
package.json
test/models/article_test.rb
yarn.lock

create accordian on the profile page for the profile

Creating article

---

app/controllers/reviews_controller.rb
app/views/hospitals/show.html.erb

error message display when criteria isn't met

Fix review bug

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_accordian.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/pages/_home.scss
app/javascript/controllers/index.js
app/models/review.rb
app/models/user.rb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/events/index.html.erb
app/views/events/new.html.erb
app/views/events/show.html.erb
app/views/hospitals/index.html.erb
app/views/hospitals/show.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/posts/index.html.erb
app/views/posts/new.html.erb
app/views/posts/show.html.erb
app/views/shared/_banner.html.erb
app/views/shared/_navbar.html.erb
app/views/users/show.html.erb
db/seeds.rb

Big changes.
Added back and log out button at the navbar;
Styled log in and sign up pages;
Added due_date field in the sign up page;
Added due_date Validation;
Styled Hospital index and show pages;
Styled Posts index and show pages;
Changed button with icon.

 Back button

---

app/assets/stylesheets/components/_alert.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_colors.scss
app/views/devise/sessions/new.html.erb
app/views/events/index.html.erb
app/views/hospitals/index.html.erb
app/views/hospitals/show.html.erb
app/views/pages/home.html.erb
app/views/shared/_banner.html.erb
app/views/shared/_navbar.html.erb
app/views/users/show.html.erb

fixed article accordian,
add confermation when log out,
moved notification alert 
move rating start below hospital location
add stars to review
add var fo navbar and banner color

Star rating

---

app/assets/stylesheets/components/_navbar.scss
app/controllers/users_controller.rb
app/views/shared/_navbar.html.erb
app/views/users/calendar.html.erb
config/environments/development.rb

Changed some of the code around the navbar buttons. It looks ok on my screen but need to check with everyone else

Navbar improvement

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_hospital_show.scss
app/assets/stylesheets/config/_colors.scss
app/views/appointments/new.html.erb
app/views/hospitals/index.html.erb
app/views/hospitals/show.html.erb
app/views/posts/new.html.erb
app/views/posts/show.html.erb

updated hospitals show 
appontment new 
and post chat

Stiling card and appointment

---

db/seeds.rb

Need to delete all the messages as well!

delete all the messages as well

---

app/views/events/index.html.erb
app/views/users/calendar.html.erb
app/views/users/show.html.erb
config/week_info.yml

moved search bar in events
added number of attendees in recommended events
fixed notes in calendar and added location
on profile page centred appointment info
added capital letters

made some adjustments

---

app/controllers/articles_controller.rb
app/models/event.rb
app/policies/article_policy.rb
app/views/articles/index.html.erb
app/views/hospitals/index.html.erb
config/routes.rb
db/seeds.rb
test/controllers/articles_controller_test.rb

Articles new seed an index page

---

app/assets/stylesheets/components/_button.scss
app/controllers/conversations_controller.rb
app/views/conversations/index.html.erb
app/views/conversations/show.html.erb
app/views/events/show.html.erb
app/views/hospitals/show.html.erb
app/views/messages/_message.html.erb
app/views/posts/show.html.erb
yarn.lock

Worked a bit on the chat style, made it more consistent with the rest of the app
Improved the margin in submit a review

Fixing chats

---

app/assets/stylesheets/components/_button.scss
app/controllers/events_controller.rb
app/controllers/posts_controller.rb
app/views/conversations/_new.html.erb
app/views/conversations/_newsmall.html.erb
app/views/events/show.html.erb
app/views/hospitals/show.html.erb
app/views/posts/show.html.erb

event host,
post creator,
reply creator,
review creator, all of them has an icon linking to the chat!

New chat icon

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_hospital_show.scss
app/controllers/appointments_controller.rb
app/controllers/events_controller.rb
app/views/appointments/new.html.erb
app/views/articles/index.html.erb
app/views/conversations/index.html.erb
app/views/events/new.html.erb
app/views/events/show.html.erb
app/views/hospitals/index.html.erb
app/views/posts/index.html.erb
db/schema.rb
db/seeds.rb

styled converstion index,
made user div clickable, had message if conversations.empty? and prevent to crash if there is a conversation with no message.
add a time range to new appointment and event

Conversations index

---

app/assets/stylesheets/components/_eventcard.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_new_appt.scss
app/views/events/index.html.erb
app/views/users/calendar.html.erb
db/schema.rb

edited calendar margin, added pinpoint location
